services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    restart: always

  redis:
    build:
      context: ./requirements/bonus/redis
    image: redis
    container_name: redis
    networks:
      - inception
    restart: always

  ftp:
    build:
      context: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    env_file:
      - .env
    ports:
      - "21:21"
      - "50000-50010:50000-50010"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

  adminer:
    build:
      context: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always

  static_site:
    build:
      context: ./requirements/bonus/static_site
    image: static_site
    container_name: static_site
    networks:
      - inception
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always

volumes:
  mariadb_data:
    name: inception_mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/moel-amr/data/mariadb
  wordpress_data:
    name: inception_wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/moel-amr/data/wordpress

networks:
  inception:
    driver: bridge